services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Scaffolder
    DsTrinityDataBundle\Resource\Scaffolder\TrinityDataScaffolder:
        tags:
            - { name: dynamic_search.resource.scaffolder, priority: 10, identifier: trinity_data_scaffolder, data_provider: trinity_data }

    # Common
    DsTrinityDataBundle\Resource\FieldTransformer\Common\ElementIdExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: element_id_extractor, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Common\ElementPropertyExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: element_property_extractor, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Common\NormalizerValueCallback:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: normalizer_value_callback, resource_scaffolder: trinity_data_scaffolder }

    # Object
    DsTrinityDataBundle\Resource\FieldTransformer\Object\ObjectGetterExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: object_getter_extractor, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Object\ObjectRelationsGetterExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: object_relations_getter_extractor, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Object\ObjectPathGenerator:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: object_path_generator, resource_scaffolder: trinity_data_scaffolder }

    # Document
    DsTrinityDataBundle\Resource\FieldTransformer\Document\DocumentMetaExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: document_meta_extractor, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Document\DocumentPathGenerator:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: document_path_generator, resource_scaffolder: trinity_data_scaffolder }

    # Asset
    DsTrinityDataBundle\Resource\FieldTransformer\Asset\PdfDataExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: asset_pdf_extractor, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Asset\AssetPathGenerator:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: asset_path_generator, resource_scaffolder: trinity_data_scaffolder }

    DsTrinityDataBundle\Resource\FieldTransformer\Asset\AssetMetaExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: asset_meta_extractor, resource_scaffolder: trinity_data_scaffolder }